baseURL = "https://michaelbalmes.com"
languageCode = "en-us"
title = "Michael Balmes"
theme = "coder-portfolio"

[params]
    author = "Michael Balmes"
    snsShare = true
    info = "Web and Infrastructure Engineer"
    avatarurl = "images/me_bw.png"
    
[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/mbalmes/"

[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/michael-balmes-070ba4107/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About me"
url = "/me"
weight = 2


[[menu.main]]
name = "Blog posts"
url = "/blog"
weight = 3

[[menu.main]]
name = "portfolio"
weight = 4
url = "portfolio"